app:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }

sport:
    path:       /sport
    defaults:   { _controller: AppBundle:Sport:index }

sport_show:
    path:       /sport/{id}
    defaults:   { _controller: AppBundle:Sport:getSport }
    requirements:
        id: '\d+'